name: CI/CD Pipeline

on:  # 定义触发条件
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:   #一个step里面包含一个或多个action
    - name: Checkout code
      uses: actions/checkout@v4  # 获取代码，加载到runner 中

    - name: Set up Node.js
      uses: actions/setup-node@v4 #在runner中安装node.js
      with:
        node-version: '20.18.0'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install  #run里面直接写bash 命令

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run backend tests
      working-directory: ./backend
      run: npm test

  deploy: # 部署
    needs: build
    runs-on: ubuntu-20.04
    environment: production

    steps:

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd SweetHome
            git restore .
            git pull
            chmod +x ./deploy.sh
            ./deploy.sh